ALTER TABLE `bl_documents`
  ADD COLUMN IF NOT EXISTS `numero_dossier` varchar(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `date_emission` date DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `validation_fxi` varchar(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `date_validation_fxi` date DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `valeur_fob` varchar(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `fret_base` varchar(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `frais_add` varchar(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `assurance` varchar(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `total_cif` varchar(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `importateur` text,
  ADD COLUMN IF NOT EXISTS `exportateur` text,
  ADD COLUMN IF NOT EXISTS `transitaire` varchar(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `armateur` varchar(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `type_transport` varchar(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `numero_voyage` varchar(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `conteneur` varchar(128) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `numero_conteneur` varchar(128) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `destination_rdc` varchar(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `eta` datetime DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `marchandise` text,
  ADD COLUMN IF NOT EXISTS `pays_provenance` varchar(128) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `code_hs` varchar(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `origine` varchar(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `poids_net` varchar(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `poids_brut` varchar(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `volume_cbm` varchar(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `teu` varchar(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `controle_par_id` int DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `controle_par` varchar(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `date_controle` datetime DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `declaration_number` varchar(128) DEFAULT NULL;
