-- Crée la table bl_documents (documents B/L extraits), sans données.
-- Même définition que bl_documents_202604061200.sql à la racine du projet.

CREATE TABLE IF NOT EXISTS `bl_documents` (
  `id` varchar(36) NOT NULL,
  `file_name` varchar(512) NOT NULL,
  `file_hash` varchar(64) NOT NULL,
  `bl_number` varchar(64) DEFAULT NULL,
  `booking_number` varchar(64) DEFAULT NULL,
  `vessel` varchar(255) DEFAULT NULL,
  `port_loading` varchar(255) DEFAULT NULL,
  `port_discharge` varchar(255) DEFAULT NULL,
  `weight` varchar(64) DEFAULT NULL,
  `raw_text` longtext,
  `status` varchar(32) NOT NULL DEFAULT 'pending',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `shipper` text,
  `consignee` text,
  `numero_dossier` varchar(64) DEFAULT NULL,
  `date_emission` date DEFAULT NULL,
  `validation_fxi` varchar(255) DEFAULT NULL,
  `date_validation_fxi` date DEFAULT NULL,
  `valeur_fob` varchar(64) DEFAULT NULL,
  `fret_base` varchar(64) DEFAULT NULL,
  `frais_add` varchar(64) DEFAULT NULL,
  `assurance` varchar(64) DEFAULT NULL,
  `total_cif` varchar(64) DEFAULT NULL,
  `importateur` text,
  `exportateur` text,
  `transitaire` varchar(255) DEFAULT NULL,
  `armateur` varchar(255) DEFAULT NULL,
  `type_transport` varchar(64) DEFAULT NULL,
  `numero_voyage` varchar(64) DEFAULT NULL,
  `conteneur` varchar(128) DEFAULT NULL,
  `numero_conteneur` varchar(128) DEFAULT NULL,
  `destination_rdc` varchar(255) DEFAULT NULL,
  `eta` datetime DEFAULT NULL,
  `marchandise` text,
  `pays_provenance` varchar(128) DEFAULT NULL,
  `code_hs` varchar(64) DEFAULT NULL,
  `origine` varchar(255) DEFAULT NULL,
  `poids_net` varchar(64) DEFAULT NULL,
  `poids_brut` varchar(64) DEFAULT NULL,
  `volume_cbm` varchar(64) DEFAULT NULL,
  `teu` varchar(64) DEFAULT NULL,
  `controle_par_id` int DEFAULT NULL,
  `controle_par` varchar(255) DEFAULT NULL,
  `date_controle` datetime DEFAULT NULL,
  `declaration_number` varchar(128) DEFAULT NULL,
  `is_exported` tinyint(1) NOT NULL DEFAULT 0,
  `is_declared` tinyint(1) NOT NULL DEFAULT 0,
  `is_validated` tinyint(1) NOT NULL DEFAULT 0,
  `annotation_controlleur` text DEFAULT NULL,
  `datetime_annotation` datetime DEFAULT NULL,
  `is_controlled_by_controller` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bl_documents_file_hash` (`file_hash`),
  KEY `idx_bl_documents_bl_number` (`bl_number`),
  KEY `idx_bl_documents_status_created` (`status`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
