-- Table des tickets professionnels issus de plaintes

CREATE TABLE IF NOT EXISTS `tbl_tickets_pro` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_ticket` VARCHAR(50) NOT NULL UNIQUE COMMENT 'Numéro unique du ticket',
  `plainte_id` INT(11) NOT NULL COMMENT 'Plainte source',
  `numero_plainte_ref` VARCHAR(50) NOT NULL COMMENT 'Numéro de plainte (snapshot)',
  `plainte_type` ENUM('Interne', 'Externe') NOT NULL COMMENT 'Type de plainte (snapshot)',
  `plainte_titre` VARCHAR(255) NOT NULL COMMENT 'Titre de la plainte (snapshot)',
  `plainte_description` TEXT NOT NULL COMMENT 'Description de la plainte (snapshot)',
  `plainte_categorie` ENUM('Service', 'Qualité', 'Sécurité', 'Ressources Humaines', 'Financier', 'Technique', 'Autre') NOT NULL DEFAULT 'Autre',
  `plainte_priorite` ENUM('Basse', 'Normale', 'Haute', 'Urgente') NOT NULL DEFAULT 'Normale',
  `plainte_statut` ENUM('Nouvelle', 'En cours', 'En attente', 'Résolue', 'Fermée', 'Rejetée') NOT NULL DEFAULT 'Nouvelle',
  `plainte_zone` VARCHAR(30) DEFAULT NULL,
  `direction_provinciale_id` INT(11) DEFAULT NULL,
  `bureau_international_id` INT(11) DEFAULT NULL,
  `plaignant_nom` VARCHAR(255) DEFAULT NULL,
  `plaignant_prenom` VARCHAR(255) DEFAULT NULL,
  `plaignant_email` VARCHAR(255) DEFAULT NULL,
  `titre` VARCHAR(255) NOT NULL COMMENT 'Titre du ticket',
  `priorite` ENUM('Basse', 'Normale', 'Haute', 'Urgente') NOT NULL DEFAULT 'Normale',
  `statut` ENUM('Ouvert', 'En cours', 'En attente', 'Résolu', 'Fermé', 'Annulé') NOT NULL DEFAULT 'Ouvert',
  `createur_id` INT(11) NOT NULL,
  `assignee_id` INT(11) DEFAULT NULL,
  `observateurs` TEXT DEFAULT NULL COMMENT 'IDs des observateurs (JSON)',
  `notes_ouverture` TEXT DEFAULT NULL,
  `date_echeance` DATETIME DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_tickets_pro_plainte` (`plainte_id`),
  KEY `idx_tickets_pro_createur` (`createur_id`),
  KEY `idx_tickets_pro_assignee` (`assignee_id`),
  KEY `idx_tickets_pro_statut` (`statut`),
  CONSTRAINT `fk_tickets_pro_plainte` FOREIGN KEY (`plainte_id`) REFERENCES `tbl_plaintes` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_tickets_pro_createur` FOREIGN KEY (`createur_id`) REFERENCES `tbl_utilisateurs` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_tickets_pro_assignee` FOREIGN KEY (`assignee_id`) REFERENCES `tbl_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_tickets_pro_direction` FOREIGN KEY (`direction_provinciale_id`) REFERENCES `tbl_directions_provinciales` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_tickets_pro_bureau` FOREIGN KEY (`bureau_international_id`) REFERENCES `tbl_bureaux_internationaux` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tickets professionnels créés à partir de plaintes';
